spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root

  flyway:
    url: ${spring.datasource.url}
    locations: classpath:db/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
